[project]
name = "apc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-api-python-client>=2.200.0",
    "google-auth>=2.57.0",
    "google-auth-httplib2>=0.4.2",
    "google-auth-oauthlib>=1.4.1",
    "gspread>=6.2.1",
    "pandas>=3.0.5",
    "pyarmor>=9.2.7",
    "pydrive2>=1.21.3",
    "pyside6>=6.11.2",
    "requests>=2.34.2",
]
